// <auto-generated />
using System;
using FitnessTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Infrastructure.Migrations
{
    [DbContext(typeof(FitnessTrackerContext))]
    [Migration("20251222104228_Enums.Update")]
    partial class EnumsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Domain.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Exercise__3214EC07669775DB");

                    b.HasIndex(new[] { "Name" }, "UQ__Exercise__737584F6875675AF")
                        .IsUnique();

                    b.ToTable("Exercise", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calories")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("Carbs")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("Fat")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id")
                        .HasName("PK__FoodItem__3214EC0739156FC4");

                    b.ToTable("FoodItem", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.FoodLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FoodId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LogDate")
                        .HasColumnType("date");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Servings")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__FoodLog__3214EC07C262DA4E");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodLog", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("GoalType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsAchieved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Goal__3214EC07B8782FE5");

                    b.HasIndex("UserId");

                    b.ToTable("Goal", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.MeasurementLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Arms")
                        .HasColumnType("int");

                    b.Property<int?>("BodyFatPercentage")
                        .HasColumnType("int");

                    b.Property<int?>("Chest")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WaistCircumference")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Measurem__3214EC073F30F966");

                    b.HasIndex("UserId");

                    b.ToTable("MeasurementLog", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07C186AAC1");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053420F4947D")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_BirthDate", "[BirthDate] <= GETDATE()");

                            t.HasCheckConstraint("CK_Users_Email_Format", "[Email] LIKE '%_@__%.__%'");

                            t.HasCheckConstraint("CK_Users_Height", "[Height] BETWEEN 50 AND 250");

                            t.HasCheckConstraint("CK_Users_MinAge", "[BirthDate] <= DATEADD(YEAR, -13, GETDATE())");

                            t.HasCheckConstraint("CK_Users_Weight", "[Weight] BETWEEN 20 AND 300");
                        });
                });

            modelBuilder.Entity("FitnessTracker.Domain.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Workout__3214EC07F7FE31E4");

                    b.HasIndex("UserId");

                    b.ToTable("Workout", null, t =>
                        {
                            t.HasCheckConstraint("CK_Workout_Date", "[Date] <= CURRENT_TIMESTAMP");

                            t.HasCheckConstraint("CK_Workout_DurationInMinutes", "[DurationInMinutes] BETWEEN 5 AND 300");
                        });
                });

            modelBuilder.Entity("FitnessTracker.Domain.WorkoutExercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("WeightUsed")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercise", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.FoodLog", b =>
                {
                    b.HasOne("FitnessTracker.Domain.FoodItem", "Food")
                        .WithMany("FoodLogs")
                        .HasForeignKey("FoodId")
                        .HasConstraintName("FK_FoodLog_FoodItem");

                    b.HasOne("FitnessTracker.Domain.User", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_FoodLog_User");

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Goal", b =>
                {
                    b.HasOne("FitnessTracker.Domain.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Goal_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Domain.MeasurementLog", b =>
                {
                    b.HasOne("FitnessTracker.Domain.User", "User")
                        .WithMany("MeasurementLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MeasurmentLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Workout", b =>
                {
                    b.HasOne("FitnessTracker.Domain.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Workout_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Domain.WorkoutExercise", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkoutExercise_Exercise");

                    b.HasOne("FitnessTracker.Domain.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkoutExercise_Workout");

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitnessTracker.Domain.FoodItem", b =>
                {
                    b.Navigation("FoodLogs");
                });

            modelBuilder.Entity("FitnessTracker.Domain.User", b =>
                {
                    b.Navigation("FoodLogs");

                    b.Navigation("Goals");

                    b.Navigation("MeasurementLogs");

                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
